backend:
  name: github
  repo: igorguida/igorguidawebsite
  branch: master

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: post
    label: "New Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # DEF The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list", default: ["category", "subcategory"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["tag1", "tag2"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "ImagePositon", name: "thumbnailImagePosition", widget: "string"}
      - {label: "Thumbnail", name: "thumbnailImage", widget: "image"}
      - {label: "CoverImage", name: "coverImage", widget: "image"}
      - {label: "Keywords", name: "keywords", widget: "list", default: ["altro", "tech"]}
